version: '3.8'

services:
  database:
    image: postgres:14.1-alpine
    container_name: postgres
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./database:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

#  backend:
#    build:
#      context: ./backend
#      dockerfile: Dockerfile
#    container_name: backend
#    depends_on:
#      database:
#        condition: service_healthy
#    env_file:
#      - .env
#    environment:
#      POSTGRES_USER: ${POSTGRES_USER}
#      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
#      POSTGRES_DB: ${POSTGRES_DB}
#      DATABASE_URL: ${DATABASE_URL}
#    ports:
#      - '3001:3000'
#    restart: always

#  frontend:
#    build:
#      context: ./frontend
#      dockerfile: Dockerfile
#    container_name: frontend
#    ports:
#      - '3000:3000'
#    depends_on:
#      - backend
#    restart: always
