version: '3.8'

services:
  database:
    image: postgres:14.1-alpine
    container_name: postgres
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./database:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    image: hamaaja/be:v13
    container_name: backend
    depends_on:
      database:
        condition: service_healthy
    env_file:
      - .env
    environment:
      DATABASE_URL: 'postgresql://postgres:1234567890@database:5432/postgres?schema=public'
    ports:
      - '3001:3001'
    restart: always
    links:
      - database

  frontend:
    image: hamaaja/fe:v8
    container_name: frontend
    ports:
      - '3000:3000'
    depends_on:
      - backend
    restart: always
